services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - figure-collection-network

  app:
    container_name: nestjs-app
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_DATABASE: project
      DB_SYNCHRONIZE: true
      DB_LOGGING: true
    networks:
      - figure-collection-network

networks:
  figure-collection-network:
    driver: bridge

volumes:
  postgres-data:
